

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class TextBlock;
                ref class Grid;
                ref class Button;
            }
        }
    }
}

namespace Chess
{
    partial ref class GameBoard : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ BlackPlayerTurn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ BlackPlayerNickname;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ BlackPlayerCheck;
        private: ::Windows::UI::Xaml::Controls::Grid^ BlackPlayerCapturedPieces;
        private: ::Windows::UI::Xaml::Controls::Grid^ PromotionGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ Board;
        private: ::Windows::UI::Xaml::Controls::Image^ WhitePlayerTurn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ WhitePlayerNickname;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ WhitePlayerCheck;
        private: ::Windows::UI::Xaml::Controls::Grid^ WhitePlayerCapturedPieces;
        private: ::Windows::UI::Xaml::Controls::Button^ saveGameButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CheckMate;
    };
}

