

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "GameBoard.xaml.h"




void ::Chess::GameBoard::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///GameBoard.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///GameBoard.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Image named 'BlackPlayerTurn'
    BlackPlayerTurn = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BlackPlayerTurn"));
    // Get the TextBlock named 'BlackPlayerNickname'
    BlackPlayerNickname = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BlackPlayerNickname"));
    // Get the TextBlock named 'BlackPlayerCheck'
    BlackPlayerCheck = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BlackPlayerCheck"));
    // Get the Grid named 'BlackPlayerCapturedPieces'
    BlackPlayerCapturedPieces = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BlackPlayerCapturedPieces"));
    // Get the Grid named 'PromotionGrid'
    PromotionGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PromotionGrid"));
    // Get the Grid named 'Board'
    Board = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Board"));
    // Get the Image named 'WhitePlayerTurn'
    WhitePlayerTurn = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"WhitePlayerTurn"));
    // Get the TextBlock named 'WhitePlayerNickname'
    WhitePlayerNickname = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"WhitePlayerNickname"));
    // Get the TextBlock named 'WhitePlayerCheck'
    WhitePlayerCheck = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"WhitePlayerCheck"));
    // Get the Grid named 'WhitePlayerCapturedPieces'
    WhitePlayerCapturedPieces = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"WhitePlayerCapturedPieces"));
    // Get the Button named 'saveGameButton'
    saveGameButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"saveGameButton"));
    // Get the TextBlock named 'CheckMate'
    CheckMate = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CheckMate"));
}

void ::Chess::GameBoard::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Chess::GameBoard::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&GameBoard::saveGameButton_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

